"""Update invitation table

Revision ID: a5fbe4c82ed8
Revises: 9ae32019f84c
Create Date: 2024-07-20 16:54:03.220532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5fbe4c82ed8'
down_revision = '9ae32019f84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('Invitation_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(),
                            autoincrement=True, nullable=False))
        batch_op.drop_column('Invitation_id')

    # ### end Alembic commands ###
