"""Initial myduka db migration.

Revision ID: 4da8b0d8ecc7
Revises: df061ddb2085
Create Date: 2024-07-15 19:24:01.124615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da8b0d8ecc7'
down_revision = 'df061ddb2085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expiry_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(create_constraint=1), nullable=True),
    sa.PrimaryKeyConstraint('invitation_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('request_date',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('request_date',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               nullable=False)

    op.drop_table('invitations')
    # ### end Alembic commands ###
