name: Flask CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}

        services:
            postgres:
                image: postgres:14-alpine
                env:
                    POSTGRES_DB: postgres
                    POSTGRES_PASSWORD: supersecretpassword
                    POSTGRES_USER: app
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.8'

            - name: Install Pipenv
              run: pip install pipenv

            - name: Install dependencies
              run: |
                  pipenv --python 3.8
                  pipenv install --dev
              working-directory: ./server

            - name: Ensure flake8 and autopep8 are installed
              run: pipenv install flake8 autopep8 --dev
              working-directory: ./server

            - name: Fix linting issues
              run: pipenv run autopep8 --in-place --aggressive --aggressive $(find . -name "*.py")
              working-directory: ./server

            - name: Run tests
              run: pipenv run pytest
              working-directory: ./server
