name: Flask CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          pipenv --python 3.8
          pipenv install --dev
        working-directory: ./server

      - name: Ensure flake8 and autopep8 are installed
        run: pipenv install flake8 autopep8 --dev
        working-directory: ./server

      - name: Fix linting issues
        run: pipenv run autopep8 --in-place --aggressive --aggressive $(find . -name "*.py")
        working-directory: ./server

      - name: Lint
        run: pipenv run flake8 .
        working-directory: ./server

      - name: Run tests
        run: pipenv run pytest
        working-directory: ./server

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: inventory_db1
          POSTGRES_USER: josephine
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run tests
        env:
          DATABASE_URL: postgresql://josephine:root@localhost:5432/inventory_db1
        run: |
          pipenv run pytest
